### ISSUE TITLE
Put a notice and link to FF57 issue

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator.github.io#8]

**Comment by timss** [comment]
Related issues:

- https://github.com/vimperator/vimperator-labs/issues/211 (somewhat)
- https://github.com/vimperator/vimperator-labs/issues/705
- https://github.com/vimperator/vimperator-labs/issues/729
- https://github.com/vimperator/vimperator-labs/issues/800

**Comment by maxauthority** [comment]
We should also add a line to the History in http://vimperator.org/about that in 2017 Vimperator basically died due to WebExtensions and e10s with the advent of FF57.

**Comment by maxauthority** [comment]
I put some (short) warning out for Firefox 57: https://addons.mozilla.org/en-US/firefox/addon/vimperator/ and http://vimperator.org/vimperator - It might not be perfect, but should get the job done, and given the links the user can get more infos if needed. So closing this issue, but feel free to reopen with improvements.
